language: node_js
cache:
  directories:
    - node_modules
os:
  - linux
before_install:
  - npm install -g --no-progress npm@latest
install:
  - npm install --no-progress
script:
  - npm run test -- -R dot
  - npm run test:integration -- -R dot
